SELECT a.ID, b.FISH_NAME, a.LENGTH
FROM FISH_INFO a
INNER JOIN FISH_NAME_INFO b ON a.FISH_TYPE = b.FISH_TYPE
WHERE a.LENGTH = (
    SELECT MAX(LENGTH)
    FROM FISH_INFO
    WHERE FISH_TYPE = a.FISH_TYPE
)
ORDER BY a.ID ASC;
